sudo: required
language: go

go:
   - 1.10.x
   - 1.11.x
   - master

script:
  - NOASM=0 make test
  - NOASM=1 make test
  - NOASM=0 make cover
  - NOASM=1 make cover

after_script:
  - bash <(curl -s https://codecov.io/bash) -t 8a75b459-85b1-4e5d-aa12-4dd705914700
