# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

.native_job: &nativejob
    docker: # run the steps with Docker
        # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
        - image: circleci/golang:${GOVER}
    steps:
        - checkout
        - run:
            name: "Run tests on Linux"
            command:
                make test

.cover_job: &coverjob
    docker: # run the steps with Docker
        # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
        - image: circleci/golang:${GOVER}
    steps:
        - checkout
        - run:
            name: "Run coverage on Linux"
            command:
                make cover

        - store_artifacts:
            path: build/coverage/coverage.html

.emulated_job: &emulatedjob
  machine: true
  steps:
    - checkout
    - run:
        name: Install the emulation handlers
        command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - run:
        name: "Testing on Linux ARM64"
        command:
            docker run --rm -v `pwd`:`pwd` -w `pwd` "flowher/debian-buster-aarch64-go" /bin/bash -c "make test"

.maintenance: &maintenance
    machine: true
    steps:
        - checkout
        - run:
            name: "Maintenance task"
            command:
                make fmtcheck
        = run:
            name: "Linting"
            command:
              curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0 &&
              golangci-lint run ./... --build-tags noasm,amd64 --enable deadcode,errcheck,gosimple,govet,ineffassign,staticcheck,structcheck,typecheck,unused,varcheck,gofmt,goconst,unconvert,gocritic,depguard,dupl,gochecknoglobals,gochecknoinits,goconst,gocritic,gocyclo,gofmt,goimports,golint,gosec,interfacer,lll,maligned,misspell,nakedret,prealloc,scopelint,stylecheck,unconvert,unparam

jobs:
    amd64:
        <<: *nativejob
        environment:
            GOVER: latest

    # Test against older version of golang
    golang_1_12:
        <<: *nativejob
        environment:
            GOVER: 1.12

    # Test for ARM64
    arm64:
        <<: *emulatedjob
        environment:

    # Coverage job
    cover:
        <<: *coverjob
        environment:
            GOVER: latest

    # ensures code is correctly formated
    maintenance:
        <<: *maintenance

workflows:
    build:
        jobs:
            - amd64
            - arm64
            - cover
            - golang_1_12
            - maintenance

